[tool.nitpick]
style = [
    "gh://mondeja/nitpick-styles/python/single-quotes.toml",
    "gh://mondeja/nitpick-styles/python/line-length-80.toml",
    "gh://mondeja/nitpick-styles/python/version/min-36.toml",
    "gh://mondeja/nitpick-styles/python/google-docstrings.toml",
    "gh://mondeja/nitpick-styles/python/readthedocs.toml"
]
