language: python
os: linux
dist: focal
cache: false
install:
  - travis_retry pip install -U tox pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
      dist: xenial
    - python: 3.7
      env: TOXENV=coveralls
      dist: bionic
      before_script:
        - pip install coveralls
      after_success:
        - coveralls
    - python: 3.8
      env: TOXENV=py38
      dist: focal
    - python: 3.7
      env: TOXENV=flake8
      dist: focal
script: tox
